### ISSUE TITLE
MATLAB 64bit and epanet

### ISSUE THREAD

**Issue by FarshidRahmani** [KIOS-Research/EPANET-Matlab-Class#2]
Hi
the 64bit Epanet DLL does not work in MATLAB.
ann error apears like this: ''Microsoft Visual C++ 2005 or 2008 is required to use this feature.''. my MATLAB is 64-bit!
Can you help me?
I tried all the 64 bit epanet2.dll files on epanet.de but they did not work.

**Comment by eldemet** [comment]
Just to answer this question in order to close it;
In the new  [Epanet Matlab Class v2.00.00](https://github.com/KIOS-Research/EPANET-Matlab-Class/tree/Version-2.0-)  we have included an automated check in order to select the most suitable compiled version of epanet.
