### ISSUE TITLE
Can I find loop in network?

### ISSUE THREAD

**Issue by kenwaka** [KIOS-Research/EPANET-Matlab-Class#32]
I have a network, in some areas, water moves in a circle(closed rounds).
For example, the flow of water in the pipes is as follows: 
From nodes 1 to 4, from 4 to 12, from 12 to 9 and from 9 to 1.
I mean (1,4,12,9) are in loop. I want to find all loop in network. Is it possible?

In other word,

I do not know how many of these closed rounds are in the network.
Is there any way , that I can find all the closed round and their indexes?

**Comment by Mariosmsk** [comment]
I believe you can write a code to find loops. Perhaps your question is better to become http://community.wateranalytics.org/

useful functions for you: 
d.getLinkNodesIndex
d.getNodesConnectingLinksID

other, fyi
https://www.mathworks.com/matlabcentral/fileexchange/10722-count-loops-in-a-graph
